language: scala

scala:
  - 2.11.0-M8
  - 2.10.3

jdk:
  - oraclejdk7
  - oraclejdk8

script: sbt ++${TRAVIS_SCALA_VERSION} test $(if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then echo "publish"; fi)

env:
  global:
    secure: "oFGpGBnIhBaqg2pbEpUtgULqzEQAjF2FCeZuPl2dPjYgPSA3vgtapueUa7JiiPEdJOjq6SNqifj92GMSUdemnzTdj4e1GAkFNmPzZyUcDnH8FtOiLJYp/HKQ1X9rvy1TmTa/1xWsBkwwvBjOoMGn07ltmbgGcZ7UTwvviLJIiSc="
    secure: "REndpJMxzGTv3DJuDPsyifI9Cic8spwzCm1UHXHD4kJXinFdROObsXgyjeY475tdeU7W827hGlRFpo2rFPgePlIOz4mXvS9hU5zbFzj7QWUHpJXvttuHm3O9KFkk8nnHJZXt9IuflBumDZ7iBLM6XgnQ9XqZ80XW347ihvN3+R0="

