language: scala

sudo: false

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers

script:
  - git config core.whitespace tab-in-indent,trailing-space,space-before-tab,cr-at-eol
  - git show --oneline --check
  - sbt "++${TRAVIS_SCALA_VERSION}!" scalafmtSbtCheck scalafmtCheck test:scalafmtCheck ${TEST_PROJECT}/test
before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
  - find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf

matrix:
  include:
  - env: TEST_PROJECT="iarrayJVM"
    scala: "2.11.12"
  - env: TEST_PROJECT="iarrayJVM"
    scala: "2.12.8"
  - env: TEST_PROJECT="iarrayJS"
    scala: "2.11.12"
  - env: TEST_PROJECT="iarrayJS"
    scala: "2.12.8"
  - env: TEST_PROJECT="iarrayNative"
    scala: "2.11.12"
    dist: trusty
    sudo: required
    before_install:
    - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
  - scala: "2.12.8"
    jdk: openjdk11
    script:
    - sbt "++${TRAVIS_SCALA_VERSION}!" iarrayJVM/test iarrayJS/test
